version: '3.3'

services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    command: /boot.sh
    restart: on-failure

  front:
    image: node:10-alpine
    command: npm run serve
    volumes:
      - ./front:/app
    working_dir: /app
    restart: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - api
    volumes:
      - ./api/media/:/media/
      - ./api/static/:/static/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro